version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/inqueue
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/codedeploy/stop_app.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/codedeploy/start_app.sh
      timeout: 300
      runas: ec2-user