services:
  inqueue-service:
    restart: always
    image: ${DOCKERHUB_USERNAME}/inqueue:latest
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATA_REDIS_HOST: docker-redis
      SPRING_DATASOURCE_HOST: docker-mysql
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MEMBER_ACCOUNT_CLIENT_ID_SIZE: ${MEMBER_ACCOUNT_CLIENT_ID_SIZE}
      MEMBER_ACCOUNT_CLIENT_SECRET_SIZE: ${MEMBER_ACCOUNT_CLIENT_SECRET_SIZE}
      JWT_TOKEN_SECRET_KEY: ${JWT_TOKEN_SECRET_KEY}
      JWT_TOKEN_EXPIRATION_MILLS: ${JWT_TOKEN_EXPIRATION_MILLS}
      AES256_SECRET_KEY: ${AES256_SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - docker-mysql
      - docker-redis
    networks:
      - inqueue

  docker-mysql:
    container_name: docker-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: inqueue
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - inqueue

  docker-redis:
    container_name: docker-redis
    image: redis:7.0.11
    ports:
      - "6379:6379"
    networks:
      - inqueue

networks:
  inqueue:
    driver: bridge
