spring:
  datasource:
    url: jdbc:mysql://${HOST}:3306/inqueue?characterEncoding=utf8
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: ture
        default_batch_fetch_size: 100
    open-in-view: false